language: php

sudo: false

cache:
  directories:
    - $HOME/.composer/cache

php:
 - 5.6
 - 7.0

env:
 global:
  - MOODLE_BRANCH=master
  - IGNORE_PATHS=amd/src/list.js,provider/powerbi/yui,Gruntfile.js

 matrix:
  - DB=pgsql
  - DB=mysqli

before_install:
  - phpenv config-rm xdebug.ini
  - cd ../..
  - composer selfupdate
  - composer create-project -n --no-dev --prefer-dist moodlerooms/moodle-plugin-ci ci dev-poet
  - export PATH="$(cd ci/bin; pwd):$(cd ci/vendor/bin; pwd):$PATH"
  - export CHROME_BIN=/usr/bin/google-chrome
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start


  - wget http://chromedriver.storage.googleapis.com/2.24/chromedriver_linux64.zip
  - mkdir $HOME/chromium-browser
  - unzip chromedriver_linux64.zip -d $HOME/chromium-browser/

install:
  - moodle-plugin-ci install
  - moodle-plugin-ci add-config -- '$CFG->behat_config = ["default" => ["extensions" => ["Behat\MinkExtension\Extension" => ["selenium2" => ["browser" => "chrome", "wd_host" => "http://localhost:4445/wd/hub"]]]]];'
  - xvfb-run -a --server-args="-screen 0 1024x768x24" java -jar ./moodle/selenium.jar -port 4445 -Dwebdriver.chrome.driver=$HOME/chromium-browser/chromedriver > /dev/null 2> /dev/null &

script:
  - moodle-plugin-ci phplint
  - moodle-plugin-ci phpcpd
  - moodle-plugin-ci phpmd
  - moodle-plugin-ci codechecker
  - moodle-plugin-ci codechecker --standard poet
  - moodle-plugin-ci csslint
  - moodle-plugin-ci shifter
  - moodle-plugin-ci jshint
  - moodle-plugin-ci validate
  - moodle-plugin-ci phpunit
  - moodle-plugin-ci behat
  - moodle-plugin-ci phpunit --coverage-text
